version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - backend

  app:
    container_name: payment-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/mydb
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: password
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/mydb
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: password

networks:
  backend:
